server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|webp|ico)$ {
    expires 365d;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  gzip on;
  gzip_types text/plain application/javascript application/x-javascript text/javascript text/css application/json application/xml;
}
