<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Api\V1\Concerns\ApiResponses;
use App\Http\Controllers\Controller;
use App\Http\Resources\Api\V1\TournamentGroupResource;
use App\Models\Competition;
use App\Models\TournamentGroup;
use Illuminate\Http\JsonResponse;

class TournamentGroupController extends Controller
{
    use ApiResponses;

    /**
     * List tournament groups for a competition. Read-only - groups are
     * generated by TournamentGroupService, not hand-authored via API.
     */
    public function index(Competition $competition): JsonResponse
    {
        $this->authorize('view', $competition->organization);

        $groups = $competition->tournamentGroups()
            ->with('standings')
            ->get();

        return $this->ok(TournamentGroupResource::collection($groups));
    }

    /**
     * Show a single tournament group.
     */
    public function show(Competition $competition, TournamentGroup $group): JsonResponse
    {
        $this->authorize('view', $competition->organization);

        abort_unless($group->competition_id === $competition->id, 404);

        $group->load('standings');

        return $this->ok(new TournamentGroupResource($group));
    }
}
